// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGMQenAtBIqY5jxA9ArUtXBZ33jC0cCwc',
    appId: '1:763658336650:android:322e364b32297e6bc83073',
    messagingSenderId: '763658336650',
    projectId: 'salehly-ea380',
    storageBucket: 'salehly-ea380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0vQaLIjAfe3wEUIcqmou-rEnMLRYwn3U',
    appId: '1:763658336650:ios:938177bff9f7f18ac83073',
    messagingSenderId: '763658336650',
    projectId: 'salehly-ea380',
    storageBucket: 'salehly-ea380.firebasestorage.app',
    androidClientId: '763658336650-0g879rhjo4faubl04ue1vo2ak065i7kf.apps.googleusercontent.com',
    iosClientId: '763658336650-jnolnre08k51cm037i0p3h8f1l7fbrg3.apps.googleusercontent.com',
    iosBundleId: 'com.salehly.user',
  );
}
